version: '3'

networks:
  composer_default:
    external: true

services:
  rest-server:
    container_name: composer-rest-server
    image: hyperledger/composer-rest-server
    networks:
      - composer_default
    ports:
      - 3001:3001
    environment:
      - COMPOSER_CARD=restadmin@ivolunteer-blockchain
      - COMPOSER_NAMESPACES=never
      - COMPOSER_AUTHENTICATION=false
      - COMPOSER_MULTIUSER=false
      - COMPOSER_TLS=false
      - COMPOSER_PORT=3001
    volumes:
        - ~/.composer:/home/composer/.composer
